In [124]:
import pandas as pd
import numpy as np
import pymorphy2
import nltk
import stop_words
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC, SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score
from sklearn.model_selection import KFold, GridSearchCV, train_test_split, cross_val_score, StratifiedKFold, ParameterGrid
from sklearn import preprocessing
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import MultiLabelBinarizer

In [81]:
data = pd.read_csv('../ucu_sentiment-master/data/train_set.csv', usecols=range(1,11),  parse_dates=['timestamp', 'thread_timestamp'])

In [82]:
data.head().T

,0,1,2,3,4
msg_id,10648620600,10648631200,10648645600,10648664700,10648667500
user_id,U0KPCJWAC,U04CH4QBD,U065VP6F7,U0KPCJWAC,U04BFDYPV
channel,_call_4_collaboration,_call_4_collaboration,_call_4_collaboration,_call_4_collaboration,_call_4_collaboration
timestamp,2016-05-17 11:30:06,2016-05-17 11:31:52,2016-05-17 11:34:16,2016-05-17 11:37:27,2016-05-17 11:37:55
text,Всем привет! У нас с <@U04BFDYPV> есть идея сд...,а почему не писать статьи в <http://ods.ai|ods...,n+1 слишком популярно и без формул?,<http://opendatascience.ru|opendatascience.ru>...,<@U065VP6F7>: Принцип примерно такой: у тебя е...
main_msg,1,1,1,1,1
thread_id,10648620600,10648631200,10648645600,10648664700,10648667500
thread_timestamp,2016-05-17 11:30:06,2016-05-17 11:31:52,2016-05-17 11:34:16,2016-05-17 11:37:27,2016-05-17 11:37:55
replies_count,0,0,0,0,0
reactions,"{'count': 6, 'name': '+1'}",{},{},{},{}

In [83]:
data =data[data.channel.isin(['career', 'big_data', 'deep_learning', 'kaggle_crackers', 
           'lang_python',  'lang_r', 'nlp', 'theory_and_practice', 'welcome', 'bayesian', '_meetings', 'datasets']) 
           & data.main_msg]

In [84]:
data.head()

,msg_id,user_id,channel,timestamp,text,main_msg,thread_id,thread_timestamp,replies_count,reactions
15251,7002610800,U040HKJE7,_meetings,2015-03-22 11:41:48,я немного заработался на этой неделе и забыл д...,1,7002610800,2015-03-22 11:41:48,0,{}
15252,7002629100,U040HKJE7,_meetings,2015-03-22 11:44:51,"теперь тизер, который я бы хотел обсудить. и п...",1,7002629100,2015-03-22 11:44:51,0,{}
15253,7002632300,U040HKJE7,_meetings,2015-03-22 11:45:23,"оно кому-нибудь надо, интересно? есть деи, мыс...",1,7002632300,2015-03-22 11:45:23,0,{}
15254,7002650700,U040HKJE7,_meetings,2015-03-22 11:48:27,за мной кстати должок перед когнитивистами. я ...,1,7002650700,2015-03-22 11:48:27,0,{}
15255,7002654400,U040HKJE7,_meetings,2015-03-22 11:49:04,...я просто могу выложить пару статей и 3 экра...,1,7002654400,2015-03-22 11:49:04,0,{}

In [85]:
mappings = {
    'career': 0,
    'theory_and_practice': 1,
    'deep_learning': 2,
    'lang_python': 3,
    '_meetings': 4,
    'kaggle_crackers': 5,
    'big_data': 6,
    'lang_r': 7,
    'nlp': 8,
    'welcome': 9,
    'datasets': 10,
    'bayesian': 11
}

In [86]:
data['channel'] = data.channel.map(mappings)
data = data.sort_values('channel').reset_index()

In [87]:
data

,index,msg_id,user_id,channel,timestamp,text,main_msg,thread_id,thread_timestamp,replies_count,reactions
0,212514,12950696802,U3HM4KY14,0,2017-02-07 22:09:28,"а если ещё сделать TDD для саентологов, то нас...",1,12950696802,2017-02-07 22:09:28,0,{}
1,199780,12591043100,U14BPHDK6,0,2016-12-28 07:07:11,срочно в <#C04DA5FUF|_jobs>! :joy:,1,12591043100,2016-12-28 07:07:11,0,{}
2,199781,12591050400,U09JEC7V0,0,2016-12-28 07:08:24,под требования канала подходит - надо постить,1,12591050400,2016-12-28 07:08:24,0,{}
3,199782,12591050700,U14BPHDK6,0,2016-12-28 07:08:27,"а, так это парт-тайм и научный сотрудник :good...",1,12591050700,2016-12-28 07:08:27,0,{}
4,199783,12591051100,U1CF22N7J,0,2016-12-28 07:08:31,"Мне кажется это лишь формально называется ""кон...",1,12591051100,2016-12-28 07:08:31,0,"{'count': 2, 'name': 'coincidence'}"
5,199784,12591056000,U0J1U64FK,0,2016-12-28 07:09:20,откуда получается число 5470?,1,12591056000,2016-12-28 07:09:20,0,"{'count': 1, 'name': 'bitcoin'}"
6,199785,12591056800,U1CF22N7J,0,2016-12-28 07:09:28,Выбор из пустого множества претендентов,1,12591056800,2016-12-28 07:09:28,0,{}
7,199786,12591059200,U1CF22N7J,0,2016-12-28 07:09:52,"Откуда? Просто зп такая, обязательно откуда-то...",1,12591059200,2016-12-28 07:09:52,0,{}
8,199787,12591059700,U14BPHDK6,0,2016-12-28 07:09:57,а что такое свидетельства программ эвм и как и...,1,12591059700,2016-12-28 07:09:57,0,{}
9,199779,12591039100,U19HATM25,0,2016-12-28 07:06:31,<http://icm.krasn.ru/page.php?page=news_2016_1...,1,12591039100,2016-12-28 07:06:31,0,"{'count': 1, 'name': 'norma'}"
10,199788,12591060700,U09JEC7V0,0,2016-12-28 07:10:07,сертификат Word,1,12591060700,2016-12-28 07:10:07,0,{}
11,199790,12591061300,U0J1U64FK,0,2016-12-28 07:10:13,чем и как обусловлено 5470? должно же быть как...,1,12591061300,2016-12-28 07:10:13,0,"{'count': 1, 'name': 'coincidence'}"
12,199791,12591062500,U14BPHDK6,0,2016-12-28 07:10:25,MAGIC,1,12591062500,2016-12-28 07:10:25,0,{}
13,199792,12591064100,U1CF22N7J,0,2016-12-28 07:10:41,"Ну блин, полная ставка у них 21880, четверть -...",1,12591064100,2016-12-28 07:10:41,0,{}
14,199793,12591064100,U0J1U64FK,0,2016-12-28 07:10:41,почему не 5500,1,12591064100,2016-12-28 07:10:41,0,{}
15,199794,12591065000,U14BPHDK6,0,2016-12-28 07:10:50,"54 года с образования кафедры, 70 лет когда-то...",1,12591065000,2016-12-28 07:10:50,0,{}
16,199795,12591065500,U1J5L3NDP,0,2016-12-28 07:10:55,"А 5470 это после налогов, да?",1,12591065500,2016-12-28 07:10:55,0,{}
17,199796,12591067000,U06J1LG1M,0,2016-12-28 07:11:10,ну просто площадь территории харьковской облас...,1,12591067000,2016-12-28 07:11:10,0,"{'count': 1, 'name': 'notbad'}"
18,199797,12591068100,U1BAKQH2M,0,2016-12-28 07:11:21,там начисляется от какой-то абстрактной базы +...,1,12591068100,2016-12-28 07:11:21,0,{}
19,199789,12591061200,U1CF22N7J,0,2016-12-28 07:10:12,Надо отнести дискету с программой на регистрацию,1,12591061200,2016-12-28 07:10:12,0,{}
20,199778,12591027100,U0J1U64FK,0,2016-12-28 07:04:31,"бенифициар выигрывает, т.к. получает больше, ч...",1,12591027100,2016-12-28 07:04:31,0,{}
21,199777,12591020000,U0J1U64FK,0,2016-12-28 07:03:20,"инвестируют обратно в компанию: в людей, в опт...",1,12591020000,2016-12-28 07:03:20,0,{}
22,199776,12591016700,U1CF22N7J,0,2016-12-28 07:02:47,"Просто не хотят платить инвесторам дивиденды, ...",1,12591016700,2016-12-28 07:02:47,0,{}
23,199757,12590960900,U0AD1L5NC,0,2016-12-28 06:53:29,"Есть еще миллиард долларов, чтобы зарыть!",1,12590960900,2016-12-28 06:53:29,0,{}
24,199758,12590961100,U06J1LG1M,0,2016-12-28 06:53:31,"причем доставка смешная, 20 баксов при цене кн...",1,12590961100,2016-12-28 06:53:31,0,{}
25,199759,12590962100,U1CF22N7J,0,2016-12-28 06:53:41,Амазон в этом плане вообще самый беспроблемный...,1,12590962100,2016-12-28 06:53:41,0,{}
26,199760,12590963000,U0J1U64FK,0,2016-12-28 06:53:50,+ все застраховано,1,12590963000,2016-12-28 06:53:50,0,{}
27,199761,12590965100,U0J1U64FK,0,2016-12-28 06:54:11,ты бы видел их маржу,1,12590965100,2016-12-28 06:54:11,0,{}
28,199762,12590965200,U14CTBLFJ,0,2016-12-28 06:54:12,"Trucker Path, вероятно, всё против Убер Фрахт....",1,12590965200,2016-12-28 06:54:12,0,{}
29,199763,12590965300,U1CF22N7J,0,2016-12-28 06:54:13,"В других местах через все круги ада пройдёшь, ...",1,12590965300,2016-12-28 06:54:13,0,{}
...,...,...,...,...,...,...,...,...,...,...,...
120967,131337,12521141700,U1LNBRZ29,11,2016-12-20 04:56:57,У нас возник спор. В статье Blundell2015 описа...,1,12521141700,2016-12-20 04:56:57,0,{}
120968,131338,12521148200,U1LNBRZ29,11,2016-12-20 04:58:02,<@U1QN13664> я скоро посмотрю про это и отвечу),1,12521148200,2016-12-20 04:58:02,0,{}
120969,131339,12521314300,U1LNBRZ29,11,2016-12-20 05:25:43,"<@U1QN13664>, в том случае это нужно было толь...",1,12521314300,2016-12-20 05:25:43,0,{}
120970,131340,12521325400,U1QN13664,11,2016-12-20 05:27:34,спасибо! ну то есть можно эту строчку было сме...,1,12521325400,2016-12-20 05:27:34,0,{}
120971,131341,12521327300,U1LNBRZ29,11,2016-12-20 05:27:53,Да,1,12521327300,2016-12-20 05:27:53,0,{}
120972,131342,12521359000,U1QN13664,11,2016-12-20 05:33:10,"кстати, насчет trace.. как-то оно в случае с в...",1,12521359000,2016-12-20 05:33:10,0,{}
120973,131343,12521360000,U1QN13664,11,2016-12-20 05:33:20,а не вот это вот сначала трейс из него генерит...,1,12521360000,2016-12-20 05:33:20,0,{}
120974,131336,12520490800,U1QN13664,11,2016-12-20 03:08:28,это ж читерство? или sample_ppc эти Y не испол...,1,12520490800,2016-12-20 03:08:28,0,{}
120975,131326,12514476100,U04423D74,11,2016-12-19 10:26:01,"коллеги, спасибо за рекомендации, буду пробовать",1,12514476100,2016-12-19 10:26:01,0,{}
120976,131325,12514321400,U0G29N5U4,11,2016-12-19 10:00:14,"А, еще можно посчитать вероятность того, что к...",1,12514321400,2016-12-19 10:00:14,0,{}
120977,131324,12514305200,U0G29N5U4,11,2016-12-19 09:57:32,"Конечно, интервалы везде возьмут. Аналог p-val...",1,12514305200,2016-12-19 09:57:32,0,"{'count': 1, 'name': '+1'}"
120978,131307,12490285900,U1LNBRZ29,11,2016-12-16 15:14:19,<@U13E1AWCX> гамильтониан из коробки не зарабо...,1,12490285900,2016-12-16 15:14:19,0,{}
120979,131308,12490292400,U1LNBRZ29,11,2016-12-16 15:15:24,Но наверно я просто не умею его готовить...,1,12490292400,2016-12-16 15:15:24,0,{}
120980,131309,12490310300,U1LNBRZ29,11,2016-12-16 15:18:23,<https://opendatascience.slack.com/archives/ba...,1,12490310300,2016-12-16 15:18:23,0,{}
120981,131310,12490315800,U0G29N5U4,11,2016-12-16 15:19:18,это вроде как конструктор? а ссылка на объект ...,1,12490315800,2016-12-16 15:19:18,0,{}
120982,131311,12490322400,U1LNBRZ29,11,2016-12-16 15:20:24,"Там хитрый перехват new, созданная переменная ...",1,12490322400,2016-12-16 15:20:24,0,{}
120983,131312,12490324900,U0G29N5U4,11,2016-12-16 15:20:49,а... ok,1,12490324900,2016-12-16 15:20:49,0,{}
120984,131313,12490329700,U1LNBRZ29,11,2016-12-16 15:21:37,"Она сама по себе она мне не нужна, нужен тольк...",1,12490329700,2016-12-16 15:21:37,0,{}
120985,131314,12490337300,U1LNBRZ29,11,2016-12-16 15:22:53,"Скорее всего диффать буду сначала и смотреть, ...",1,12490337300,2016-12-16 15:22:53,0,{}
120986,131315,12490344100,U1LNBRZ29,11,2016-12-16 15:24:01,Ещё советуют затюнить nuts попробовать,1,12490344100,2016-12-16 15:24:01,0,{}
120987,131316,12498548100,U1LNBRZ29,11,2016-12-17 14:11:21,"Сделал с разностями, теперь доверительные инте...",1,12498548100,2016-12-17 14:11:21,0,"{'count': 2, 'name': 'but_why'}"
120988,131317,12506594300,U1LNBRZ29,11,2016-12-18 12:32:23,Все получилось после нормализаций и логарифмир...,1,12506594300,2016-12-18 12:32:23,0,"{'count': 1, 'name': '+1'}"
120989,131318,12513850800,U04423D74,11,2016-12-19 08:41:48,"коллеги, скажи, а как репортить результаты бай...",1,12513850800,2016-12-19 08:41:48,0,{}
120990,131319,12513974700,U2GTUS0CB,11,2016-12-19 09:02:27,Вместо p-value можно указывать доверительные и...,1,12513974700,2016-12-19 09:02:27,0,"{'count': 1, 'name': 'heavy_plus_sign'}"
120991,131320,12513997200,U04423D74,11,2016-12-19 09:06:12,"боюсь, редакторов журналов это не очень устрои...",1,12513997200,2016-12-19 09:06:12,0,{}
120992,131321,12514048600,U2GTUS0CB,11,2016-12-19 09:14:46,Один из вариантов - это напрямую спросить разр...,1,12514048600,2016-12-19 09:14:46,0,{}
120993,131322,12514057200,U04423D74,11,2016-12-19 09:16:12,"упаси бог от гельмана, он злобный тип, а я сли...",1,12514057200,2016-12-19 09:16:12,0,{}
120994,131323,12514165200,U1CF22N7J,11,2016-12-19 09:34:12,"Credible intervals же круче на порядок, чем p-...",1,12514165200,2016-12-19 09:34:12,0,{}
120995,131425,12656832700,U1LNBRZ29,11,2017-01-04 21:52:07,"сап чат, я тут вникаю в суть OPVI и не могу по...",1,12656832700,2017-01-04 21:52:07,0,{}
120996,130464,11081929500,U04URBM8V,11,2016-07-06 15:08:15,"Именно, можете кидать ссылки и формулы на самы...",1,11081929500,2016-07-06 15:08:15,0,"{'count': 1, 'name': 'math'}"

In [88]:
data.text.isnull().sum()

56

In [89]:
data[data.isnull().any(axis=1)]

,index,msg_id,user_id,channel,timestamp,text,main_msg,thread_id,thread_timestamp,replies_count,reactions
3807,203379,12786900400,U14BPHDK6,0,2017-01-19 23:10:04,NaN,1,12786900400,2017-01-19 23:10:04,0,{}
8915,197051,12448604000,U14BPHDK6,0,2016-12-11 19:27:20,NaN,1,12448604000,2016-12-11 19:27:20,0,{}
12874,224165,13249950110,U041SH27M,0,2017-03-14 13:25:01,NaN,1,13249950110,2017-03-14 13:25:01,0,{}
13421,215586,13078688503,U1NLYUY5N,0,2017-02-22 17:41:25,NaN,1,13078688503,2017-02-22 17:41:25,1,{}
13423,215588,13078691903,U1NLYUY5N,0,2017-02-22 17:41:59,NaN,1,13078691903,2017-02-22 17:41:59,0,{}
15830,239438,14034833584,U040HKJE7,0,2017-06-13 09:38:55,NaN,1,14034833584,2017-06-13 09:38:55,26,"{'count': 1, 'name': '+1'}"
16787,231026,13534290048,U1CF22N7J,0,2017-04-16 11:15:00,NaN,1,13534290048,2017-04-16 11:15:00,1,{}
17365,229374,13450639038,U3Z5KPTRQ,0,2017-04-06 18:53:10,NaN,1,13450639038,2017-04-06 18:53:10,0,{}
18208,208415,12845433001,U14BPHDK6,0,2017-01-26 17:45:30,NaN,1,12845433001,2017-01-26 17:45:30,0,{}
19898,206258,12829060401,U1NLYUY5N,0,2017-01-24 20:16:44,NaN,1,12829060401,2017-01-24 20:16:44,0,{}
20086,204747,12819443001,U1CF95PP1,0,2017-01-23 17:33:50,NaN,1,12819443001,2017-01-23 17:33:50,0,{}
26327,191312,11996633600,U1ULFPM0U,0,2016-10-20 11:58:56,NaN,1,11996633600,2016-10-20 11:58:56,0,{}
34376,427177,13828767885,U3NTP0Q58,1,2017-05-20 13:14:38,NaN,1,13828767885,2017-05-20 13:14:38,4,"{'count': 2, 'name': 'facepalm'}"
34804,428618,14158692355,U486G53GT,1,2017-06-27 17:42:03,NaN,1,14158692355,2017-06-27 17:42:03,14,{}
36814,422021,12769056800,U1ZAJ4FC4,1,2017-01-17 21:36:08,NaN,1,12769056800,2017-01-17 21:36:08,0,{}
37889,425103,13387094398,U44FD6Q66,1,2017-03-30 10:22:23,NaN,1,13387094398,2017-03-30 10:22:23,0,{}
46263,413329,10916996000,U17S9F6KV,1,2016-06-17 12:59:20,NaN,1,10916996000,2016-06-17 12:59:20,0,{}
49542,266243,12734336800,U0ZHHV83C,2,2017-01-13 21:09:28,NaN,1,12734336800,2017-01-13 21:09:28,0,{}
49704,266760,12803354700,U04ELQZAU,2,2017-01-21 20:52:27,NaN,1,12803354700,2017-01-21 20:52:27,0,"{'count': 8, 'name': '+1'}"
50261,266202,12733069500,U07V1URT9,2,2017-01-13 17:38:15,NaN,1,12733069500,2017-01-13 17:38:15,0,{}
50972,263326,12195812500,U04ELQZAU,2,2016-11-12 13:15:25,NaN,1,12195812500,2016-11-12 13:15:25,0,"{'count': 3, 'name': 'take-my-money'}"
51710,264082,12331670300,U07159GKF,2,2016-11-28 06:38:23,NaN,1,12331670300,2016-11-28 06:38:23,0,{}
54063,275725,14304094521,U0ZJV6E5Q,2,2017-07-14 13:35:45,NaN,1,14304094521,2017-07-14 13:35:45,0,"{'count': 3, 'name': 'tf'}"
54758,272779,13805892109,U411PKASW,2,2017-05-17 21:42:01,NaN,1,13805892109,2017-05-17 21:42:01,0,{}
55000,267452,12855612800,U04ELQZAU,2,2017-01-27 22:02:08,NaN,1,12855612800,2017-01-27 22:02:08,0,"{'count': 3, 'name': '+1'}"
55287,267716,12878637700,U04ELQZAU,2,2017-01-30 13:59:37,NaN,1,12878637700,2017-01-30 13:59:37,0,"{'count': 1, 'name': 'bayes'}"
61481,260930,11306309800,U04DXFZ2G,2,2016-08-01 14:24:58,NaN,1,11306309800,2016-08-01 14:24:58,0,{}
62768,262219,11765097700,U04ELQZAU,2,2016-09-23 16:49:37,NaN,1,11765097700,2016-09-23 16:49:37,0,"{'count': 1, 'name': '+1'}"
75563,338166,13248463206,U3B7T7V8W,3,2017-03-14 09:17:12,NaN,1,13248463206,2017-03-14 09:17:12,0,{}
75633,338316,13268387863,U1NMKU9DY,3,2017-03-16 16:37:58,NaN,1,13268387863,2017-03-16 16:37:58,0,{}
76798,332163,11453099500,U0M39M6LS,3,2016-08-18 14:09:55,NaN,1,11453099500,2016-08-18 14:09:55,0,{}
81802,25334,12766559100,U040HKJE7,4,2017-01-17 14:39:51,NaN,1,12766559100,2017-01-17 14:39:51,0,{}
81932,25574,12984129700,U073056E4,4,2017-02-11 19:01:37,NaN,1,12984129700,2017-02-11 19:01:37,6,{}
83131,24001,12056550900,U040HKJE7,4,2016-10-27 10:25:09,NaN,1,12056550900,2016-10-27 10:25:09,0,{}
83301,24170,12185945400,U0M39M6LS,4,2016-11-11 09:50:54,NaN,1,12185945400,2016-11-11 09:50:54,0,{}
83700,24733,12341832000,U2T5N5UAK,4,2016-11-29 10:52:00,NaN,1,12341832000,2016-11-29 10:52:00,0,{}
91027,313512,12215111900,U07V1URT9,5,2016-11-14 18:51:59,NaN,1,12215111900,2016-11-14 18:51:59,0,"{'count': 1, 'name': '+1'}"
91028,313511,12215109800,U07V1URT9,5,2016-11-14 18:51:38,NaN,1,12215109800,2016-11-14 18:51:38,0,"{'count': 1, 'name': '+1'}"
95108,318586,13519736454,U049HDR2Z,5,2017-04-14 18:49:24,NaN,1,13519736454,2017-04-14 18:49:24,2,"{'count': 9, 'name': '+1'}"
96456,321415,14160242790,U07V1URT9,5,2017-06-27 22:00:27,NaN,1,14160242790,2017-06-27 22:00:27,0,{}
97450,314893,12768652500,U04725QK7,5,2017-01-17 20:28:45,NaN,1,12768652500,2017-01-17 20:28:45,0,{}
97654,315156,12792413000,U040HKJE7,5,2017-01-20 14:28:50,NaN,1,12792413000,2017-01-20 14:28:50,0,{}
99079,316731,13062387000,U1SJSB014,5,2017-02-20 20:24:30,NaN,1,13062387000,2017-02-20 20:24:30,0,{}
104181,137423,13189936100,U2AM8PRMM,6,2017-03-07 14:42:41,NaN,1,13189936100,2017-03-07 14:42:41,1,{}
106056,345729,12040493300,U040HKJE7,7,2016-10-25 13:48:53,NaN,1,12040493300,2016-10-25 13:48:53,0,{}
106222,346188,12266347500,U040HKJE7,7,2016-11-20 17:11:15,NaN,1,12266347500,2016-11-20 17:11:15,0,"{'count': 1, 'name': 'metal'}"
106237,346189,12266349200,U040HKJE7,7,2016-11-20 17:11:32,NaN,1,12266349200,2016-11-20 17:11:32,0,{}
107568,347420,13207281034,U040HKJE7,7,2017-03-09 14:53:30,NaN,1,13207281034,2017-03-09 14:53:30,0,"{'count': 6, 'name': '+1'}"
113232,369962,13970440544,U04JHD4QK,8,2017-06-05 22:46:45,NaN,1,13970440544,2017-06-05 22:46:45,2,{}
113311,368398,13178840300,U0M39M6LS,8,2017-03-06 07:53:23,NaN,1,13178840300,2017-03-06 07:53:23,0,{}
114592,366795,12367213000,U14BPHDK6,8,2016-12-02 09:22:10,NaN,1,12367213000,2016-12-02 09:22:10,0,"{'count': 2, 'name': '+1'}"
118927,253486,13862779071,U049HDR2Z,10,2017-05-24 11:43:10,NaN,1,13862779071,2017-05-24 11:43:10,0,{}
119087,253330,13517568561,U2GAEHQR1,10,2017-04-14 12:48:05,NaN,1,13517568561,2017-04-14 12:48:05,1,"{'count': 1, 'name': 'up'}"
119410,252601,12698417200,U14BPHDK6,10,2017-01-09 17:22:52,NaN,1,12698417200,2017-01-09 17:22:52,0,"{'count': 2, 'name': 'joy'}"
119441,252632,12712176500,U3B7T7V8W,10,2017-01-11 07:36:05,NaN,1,12712176500,2017-01-11 07:36:05,0,{}
120001,131013,12195814400,U04ELQZAU,11,2016-11-12 13:15:44,NaN,1,12195814400,2016-11-12 13:15:44,0,"{'count': 10, 'name': '+1'}"

In [90]:
# parameters initialization
VALIDATION_SPLIT = 0.1
RANDOM_SEED = 42

In [91]:
data = data.dropna()

In [92]:
data

,index,msg_id,user_id,channel,timestamp,text,main_msg,thread_id,thread_timestamp,replies_count,reactions
0,212514,12950696802,U3HM4KY14,0,2017-02-07 22:09:28,"а если ещё сделать TDD для саентологов, то нас...",1,12950696802,2017-02-07 22:09:28,0,{}
1,199780,12591043100,U14BPHDK6,0,2016-12-28 07:07:11,срочно в <#C04DA5FUF|_jobs>! :joy:,1,12591043100,2016-12-28 07:07:11,0,{}
2,199781,12591050400,U09JEC7V0,0,2016-12-28 07:08:24,под требования канала подходит - надо постить,1,12591050400,2016-12-28 07:08:24,0,{}
3,199782,12591050700,U14BPHDK6,0,2016-12-28 07:08:27,"а, так это парт-тайм и научный сотрудник :good...",1,12591050700,2016-12-28 07:08:27,0,{}
4,199783,12591051100,U1CF22N7J,0,2016-12-28 07:08:31,"Мне кажется это лишь формально называется ""кон...",1,12591051100,2016-12-28 07:08:31,0,"{'count': 2, 'name': 'coincidence'}"
5,199784,12591056000,U0J1U64FK,0,2016-12-28 07:09:20,откуда получается число 5470?,1,12591056000,2016-12-28 07:09:20,0,"{'count': 1, 'name': 'bitcoin'}"
6,199785,12591056800,U1CF22N7J,0,2016-12-28 07:09:28,Выбор из пустого множества претендентов,1,12591056800,2016-12-28 07:09:28,0,{}
7,199786,12591059200,U1CF22N7J,0,2016-12-28 07:09:52,"Откуда? Просто зп такая, обязательно откуда-то...",1,12591059200,2016-12-28 07:09:52,0,{}
8,199787,12591059700,U14BPHDK6,0,2016-12-28 07:09:57,а что такое свидетельства программ эвм и как и...,1,12591059700,2016-12-28 07:09:57,0,{}
9,199779,12591039100,U19HATM25,0,2016-12-28 07:06:31,<http://icm.krasn.ru/page.php?page=news_2016_1...,1,12591039100,2016-12-28 07:06:31,0,"{'count': 1, 'name': 'norma'}"
10,199788,12591060700,U09JEC7V0,0,2016-12-28 07:10:07,сертификат Word,1,12591060700,2016-12-28 07:10:07,0,{}
11,199790,12591061300,U0J1U64FK,0,2016-12-28 07:10:13,чем и как обусловлено 5470? должно же быть как...,1,12591061300,2016-12-28 07:10:13,0,"{'count': 1, 'name': 'coincidence'}"
12,199791,12591062500,U14BPHDK6,0,2016-12-28 07:10:25,MAGIC,1,12591062500,2016-12-28 07:10:25,0,{}
13,199792,12591064100,U1CF22N7J,0,2016-12-28 07:10:41,"Ну блин, полная ставка у них 21880, четверть -...",1,12591064100,2016-12-28 07:10:41,0,{}
14,199793,12591064100,U0J1U64FK,0,2016-12-28 07:10:41,почему не 5500,1,12591064100,2016-12-28 07:10:41,0,{}
15,199794,12591065000,U14BPHDK6,0,2016-12-28 07:10:50,"54 года с образования кафедры, 70 лет когда-то...",1,12591065000,2016-12-28 07:10:50,0,{}
16,199795,12591065500,U1J5L3NDP,0,2016-12-28 07:10:55,"А 5470 это после налогов, да?",1,12591065500,2016-12-28 07:10:55,0,{}
17,199796,12591067000,U06J1LG1M,0,2016-12-28 07:11:10,ну просто площадь территории харьковской облас...,1,12591067000,2016-12-28 07:11:10,0,"{'count': 1, 'name': 'notbad'}"
18,199797,12591068100,U1BAKQH2M,0,2016-12-28 07:11:21,там начисляется от какой-то абстрактной базы +...,1,12591068100,2016-12-28 07:11:21,0,{}
19,199789,12591061200,U1CF22N7J,0,2016-12-28 07:10:12,Надо отнести дискету с программой на регистрацию,1,12591061200,2016-12-28 07:10:12,0,{}
20,199778,12591027100,U0J1U64FK,0,2016-12-28 07:04:31,"бенифициар выигрывает, т.к. получает больше, ч...",1,12591027100,2016-12-28 07:04:31,0,{}
21,199777,12591020000,U0J1U64FK,0,2016-12-28 07:03:20,"инвестируют обратно в компанию: в людей, в опт...",1,12591020000,2016-12-28 07:03:20,0,{}
22,199776,12591016700,U1CF22N7J,0,2016-12-28 07:02:47,"Просто не хотят платить инвесторам дивиденды, ...",1,12591016700,2016-12-28 07:02:47,0,{}
23,199757,12590960900,U0AD1L5NC,0,2016-12-28 06:53:29,"Есть еще миллиард долларов, чтобы зарыть!",1,12590960900,2016-12-28 06:53:29,0,{}
24,199758,12590961100,U06J1LG1M,0,2016-12-28 06:53:31,"причем доставка смешная, 20 баксов при цене кн...",1,12590961100,2016-12-28 06:53:31,0,{}
25,199759,12590962100,U1CF22N7J,0,2016-12-28 06:53:41,Амазон в этом плане вообще самый беспроблемный...,1,12590962100,2016-12-28 06:53:41,0,{}
26,199760,12590963000,U0J1U64FK,0,2016-12-28 06:53:50,+ все застраховано,1,12590963000,2016-12-28 06:53:50,0,{}
27,199761,12590965100,U0J1U64FK,0,2016-12-28 06:54:11,ты бы видел их маржу,1,12590965100,2016-12-28 06:54:11,0,{}
28,199762,12590965200,U14CTBLFJ,0,2016-12-28 06:54:12,"Trucker Path, вероятно, всё против Убер Фрахт....",1,12590965200,2016-12-28 06:54:12,0,{}
29,199763,12590965300,U1CF22N7J,0,2016-12-28 06:54:13,"В других местах через все круги ада пройдёшь, ...",1,12590965300,2016-12-28 06:54:13,0,{}
...,...,...,...,...,...,...,...,...,...,...,...
120967,131337,12521141700,U1LNBRZ29,11,2016-12-20 04:56:57,У нас возник спор. В статье Blundell2015 описа...,1,12521141700,2016-12-20 04:56:57,0,{}
120968,131338,12521148200,U1LNBRZ29,11,2016-12-20 04:58:02,<@U1QN13664> я скоро посмотрю про это и отвечу),1,12521148200,2016-12-20 04:58:02,0,{}
120969,131339,12521314300,U1LNBRZ29,11,2016-12-20 05:25:43,"<@U1QN13664>, в том случае это нужно было толь...",1,12521314300,2016-12-20 05:25:43,0,{}
120970,131340,12521325400,U1QN13664,11,2016-12-20 05:27:34,спасибо! ну то есть можно эту строчку было сме...,1,12521325400,2016-12-20 05:27:34,0,{}
120971,131341,12521327300,U1LNBRZ29,11,2016-12-20 05:27:53,Да,1,12521327300,2016-12-20 05:27:53,0,{}
120972,131342,12521359000,U1QN13664,11,2016-12-20 05:33:10,"кстати, насчет trace.. как-то оно в случае с в...",1,12521359000,2016-12-20 05:33:10,0,{}
120973,131343,12521360000,U1QN13664,11,2016-12-20 05:33:20,а не вот это вот сначала трейс из него генерит...,1,12521360000,2016-12-20 05:33:20,0,{}
120974,131336,12520490800,U1QN13664,11,2016-12-20 03:08:28,это ж читерство? или sample_ppc эти Y не испол...,1,12520490800,2016-12-20 03:08:28,0,{}
120975,131326,12514476100,U04423D74,11,2016-12-19 10:26:01,"коллеги, спасибо за рекомендации, буду пробовать",1,12514476100,2016-12-19 10:26:01,0,{}
120976,131325,12514321400,U0G29N5U4,11,2016-12-19 10:00:14,"А, еще можно посчитать вероятность того, что к...",1,12514321400,2016-12-19 10:00:14,0,{}
120977,131324,12514305200,U0G29N5U4,11,2016-12-19 09:57:32,"Конечно, интервалы везде возьмут. Аналог p-val...",1,12514305200,2016-12-19 09:57:32,0,"{'count': 1, 'name': '+1'}"
120978,131307,12490285900,U1LNBRZ29,11,2016-12-16 15:14:19,<@U13E1AWCX> гамильтониан из коробки не зарабо...,1,12490285900,2016-12-16 15:14:19,0,{}
120979,131308,12490292400,U1LNBRZ29,11,2016-12-16 15:15:24,Но наверно я просто не умею его готовить...,1,12490292400,2016-12-16 15:15:24,0,{}
120980,131309,12490310300,U1LNBRZ29,11,2016-12-16 15:18:23,<https://opendatascience.slack.com/archives/ba...,1,12490310300,2016-12-16 15:18:23,0,{}
120981,131310,12490315800,U0G29N5U4,11,2016-12-16 15:19:18,это вроде как конструктор? а ссылка на объект ...,1,12490315800,2016-12-16 15:19:18,0,{}
120982,131311,12490322400,U1LNBRZ29,11,2016-12-16 15:20:24,"Там хитрый перехват new, созданная переменная ...",1,12490322400,2016-12-16 15:20:24,0,{}
120983,131312,12490324900,U0G29N5U4,11,2016-12-16 15:20:49,а... ok,1,12490324900,2016-12-16 15:20:49,0,{}
120984,131313,12490329700,U1LNBRZ29,11,2016-12-16 15:21:37,"Она сама по себе она мне не нужна, нужен тольк...",1,12490329700,2016-12-16 15:21:37,0,{}
120985,131314,12490337300,U1LNBRZ29,11,2016-12-16 15:22:53,"Скорее всего диффать буду сначала и смотреть, ...",1,12490337300,2016-12-16 15:22:53,0,{}
120986,131315,12490344100,U1LNBRZ29,11,2016-12-16 15:24:01,Ещё советуют затюнить nuts попробовать,1,12490344100,2016-12-16 15:24:01,0,{}
120987,131316,12498548100,U1LNBRZ29,11,2016-12-17 14:11:21,"Сделал с разностями, теперь доверительные инте...",1,12498548100,2016-12-17 14:11:21,0,"{'count': 2, 'name': 'but_why'}"
120988,131317,12506594300,U1LNBRZ29,11,2016-12-18 12:32:23,Все получилось после нормализаций и логарифмир...,1,12506594300,2016-12-18 12:32:23,0,"{'count': 1, 'name': '+1'}"
120989,131318,12513850800,U04423D74,11,2016-12-19 08:41:48,"коллеги, скажи, а как репортить результаты бай...",1,12513850800,2016-12-19 08:41:48,0,{}
120990,131319,12513974700,U2GTUS0CB,11,2016-12-19 09:02:27,Вместо p-value можно указывать доверительные и...,1,12513974700,2016-12-19 09:02:27,0,"{'count': 1, 'name': 'heavy_plus_sign'}"
120991,131320,12513997200,U04423D74,11,2016-12-19 09:06:12,"боюсь, редакторов журналов это не очень устрои...",1,12513997200,2016-12-19 09:06:12,0,{}
120992,131321,12514048600,U2GTUS0CB,11,2016-12-19 09:14:46,Один из вариантов - это напрямую спросить разр...,1,12514048600,2016-12-19 09:14:46,0,{}
120993,131322,12514057200,U04423D74,11,2016-12-19 09:16:12,"упаси бог от гельмана, он злобный тип, а я сли...",1,12514057200,2016-12-19 09:16:12,0,{}
120994,131323,12514165200,U1CF22N7J,11,2016-12-19 09:34:12,"Credible intervals же круче на порядок, чем p-...",1,12514165200,2016-12-19 09:34:12,0,{}
120995,131425,12656832700,U1LNBRZ29,11,2017-01-04 21:52:07,"сап чат, я тут вникаю в суть OPVI и не могу по...",1,12656832700,2017-01-04 21:52:07,0,{}
120996,130464,11081929500,U04URBM8V,11,2016-07-06 15:08:15,"Именно, можете кидать ссылки и формулы на самы...",1,11081929500,2016-07-06 15:08:15,0,"{'count': 1, 'name': 'math'}"

In [93]:
from datetime import date
import fastnumbers

In [94]:
data.head(10)

,index,msg_id,user_id,channel,timestamp,text,main_msg,thread_id,thread_timestamp,replies_count,reactions
0,212514,12950696802,U3HM4KY14,0,2017-02-07 22:09:28,"а если ещё сделать TDD для саентологов, то нас...",1,12950696802,2017-02-07 22:09:28,0,{}
1,199780,12591043100,U14BPHDK6,0,2016-12-28 07:07:11,срочно в <#C04DA5FUF|_jobs>! :joy:,1,12591043100,2016-12-28 07:07:11,0,{}
2,199781,12591050400,U09JEC7V0,0,2016-12-28 07:08:24,под требования канала подходит - надо постить,1,12591050400,2016-12-28 07:08:24,0,{}
3,199782,12591050700,U14BPHDK6,0,2016-12-28 07:08:27,"а, так это парт-тайм и научный сотрудник :good...",1,12591050700,2016-12-28 07:08:27,0,{}
4,199783,12591051100,U1CF22N7J,0,2016-12-28 07:08:31,"Мне кажется это лишь формально называется ""кон...",1,12591051100,2016-12-28 07:08:31,0,"{'count': 2, 'name': 'coincidence'}"
5,199784,12591056000,U0J1U64FK,0,2016-12-28 07:09:20,откуда получается число 5470?,1,12591056000,2016-12-28 07:09:20,0,"{'count': 1, 'name': 'bitcoin'}"
6,199785,12591056800,U1CF22N7J,0,2016-12-28 07:09:28,Выбор из пустого множества претендентов,1,12591056800,2016-12-28 07:09:28,0,{}
7,199786,12591059200,U1CF22N7J,0,2016-12-28 07:09:52,"Откуда? Просто зп такая, обязательно откуда-то...",1,12591059200,2016-12-28 07:09:52,0,{}
8,199787,12591059700,U14BPHDK6,0,2016-12-28 07:09:57,а что такое свидетельства программ эвм и как и...,1,12591059700,2016-12-28 07:09:57,0,{}
9,199779,12591039100,U19HATM25,0,2016-12-28 07:06:31,<http://icm.krasn.ru/page.php?page=news_2016_1...,1,12591039100,2016-12-28 07:06:31,0,"{'count': 1, 'name': 'norma'}"

In [95]:
# data_train = data.
date_before = date(2017, 4, 1)
train = data[data['timestamp'] < date_before]
val = data[data['timestamp'] > date_before]

In [96]:
train_data = train[['channel', 'text']].reset_index()[['channel', 'text']]
train_data = train_data.sort_values('channel').reset_index()[['channel', 'text']]

val_data = val[['channel', 'text']].reset_index()[['channel', 'text']]
val_data = val_data.sort_values('channel').reset_index()[['channel', 'text']]

from fastnumbers import isfloat, isint
train_data = train_data[~train_data.text.apply(lambda x: isfloat(x) or isint(x) or len(x) < 20)]
val_data = val_data[~val_data.text.apply(lambda x: isfloat(x) or isint(x) or len(x) < 20)]

train_text = train_data['text'].astype(str)
train_labels =  np.asarray(train_data['channel'], dtype='int8')

val_text = val_data['text'].astype(str)
val_labels = np.asarray(val_data['channel'], dtype='int8')

In [128]:
morph = pymorphy2.MorphAnalyzer()

In [140]:
train_text_lem = []
for sentence in train_text:
    train_text_lem.append([])
    for word in nltk.word_tokenize(sentence):
        if word not in stopwords.words('russian'):
            train_text_lem[-1].append(morph.parse(word)[0].normal_form)

In [157]:
train_text_lem_1 = [" ".join(i) for i in train_text_lem]

In [142]:
val_text_lem = []
for sentence in val_text:
    val_text_lem.append([])
    for word in nltk.word_tokenize(sentence):
        if word not in stopwords.words('russian'):
            val_text_lem[-1].append(morph.parse(word)[0].normal_form)

In [145]:
# without tuning accuracy_score = 50.81%
# accuracy_score = 58.26%
classifier = Pipeline([
    ('vectorizer', TfidfVectorizer(analyzer = 'char', max_features = 1000000, 
                                                       ngram_range = (1, 4))),
    ('clf', OneVsRestClassifier(LinearSVC(),n_jobs=-1))])

In [99]:
classifier.fit(train_text, train_labels)

Pipeline(steps=[('vectorizer', TfidfVectorizer(analyzer='char', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=1000000, min_df=1,
        ngram_range=(1, 4), norm='l2', preprocessor=None, smooth_idf...ti_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0),
          n_jobs=-1))])

In [160]:
classifier.fit([" ".join(i) for i in train_text_lem], train_labels)

Pipeline(steps=[('vectorizer', TfidfVectorizer(analyzer='char', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=1000000, min_df=1,
        ngram_range=(1, 4), norm='l2', preprocessor=None, smooth_idf...ti_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0),
          n_jobs=-1))])

In [162]:
predicted = classifier.predict([" ".join(i) for i in val_text_lem])

In [163]:
accuracy_score(predicted, val_labels)

0.58085365853658533

In [164]:
pd.crosstab(predicted, val_labels, rownames=['True'], colnames=['Predicted'], margins=True)

Predicted     0    1     2    3    4     5    6    7    8    9   10  11   All
True
0          1660   97   147   54   15   473   31    8   35   19   14   4  2557
1           117  501   146  148    7   231   27   18   70    2   21  25  1313
2            79   84   707   75    9   245   13   16   63    2   18  15  1326
3            51  106   104  514    3    69   30   25   26    1    6   6   941
4            75   12    18   13  133    72    6    5    5    3    8   3   353
5            28   35    32   21    3   585    4    5   16    0    6   2   737
6            17    8    10   14    1    19  156    5    1    1    2   1   235
7            13    9     5   14    4    11    4  118    2    0    2   2   184
8             6   14    17   10    0    16    2    3  142    0   15   0   225
9            12    7     4    4    4     6    1    2    4  184    1   0   229
10            2    5     6    3    0     3    1    0    9    0   49   0    78
11            0    3     3    1    0     1    0    0    0    0    0  14    22
All        2060  881  1199  871  179  1731  275  205  373  212  142  72  8200

In [146]:
param_grid = {"min_df": [1,3,5],
              "max_features": [100000, 1000000],
              "ngram_range":[(1,2), (1,3), (1,4)]}

In [147]:
grid = ParameterGrid(param_grid)

In [148]:
for params in grid:
    classifier = Pipeline([
                        ('vectorizer', CountVectorizer(min_df = params['min_df'], max_features = params['max_features'], 
                                                       ngram_range = params['ngram_range'])),
                        ('clf', OneVsRestClassifier(LinearSVC()))])
    classifier.fit(data_train, labels_train)
    predicted = classifier.predict(data_test)
    accuracy = accuracy_score(predicted, labels_test)
    print('Parameters: {}\n Score:{}'.format(params, accuracy))

Parameters: {'min_df': 1, 'max_features': 100000, 'ngram_range': (1, 2)}
 Score:0.4976190476190476
Parameters: {'min_df': 1, 'max_features': 100000, 'ngram_range': (1, 3)}
 Score:0.495
Parameters: {'min_df': 1, 'max_features': 100000, 'ngram_range': (1, 4)}
 Score:0.4955555555555556
Parameters: {'min_df': 3, 'max_features': 100000, 'ngram_range': (1, 2)}
 Score:0.49563492063492065
Parameters: {'min_df': 3, 'max_features': 100000, 'ngram_range': (1, 3)}
 Score:0.49603174603174605
Parameters: {'min_df': 3, 'max_features': 100000, 'ngram_range': (1, 4)}
 Score:0.4946031746031746
Parameters: {'min_df': 5, 'max_features': 100000, 'ngram_range': (1, 2)}
 Score:0.48507936507936505
Parameters: {'min_df': 5, 'max_features': 100000, 'ngram_range': (1, 3)}
 Score:0.48563492063492064
Parameters: {'min_df': 5, 'max_features': 100000, 'ngram_range': (1, 4)}
 Score:0.4847619047619048
Parameters: {'min_df': 1, 'max_features': 1000000, 'ngram_range': (1, 2)}
 Score:0.5063492063492063
Parameters: {'min_df': 1, 'max_features': 1000000, 'ngram_range': (1, 3)}
 Score:0.5018253968253968
Parameters: {'min_df': 1, 'max_features': 1000000, 'ngram_range': (1, 4)}
 Score:0.49984126984126986
Parameters: {'min_df': 3, 'max_features': 1000000, 'ngram_range': (1, 2)}
 Score:0.49563492063492065
Parameters: {'min_df': 3, 'max_features': 1000000, 'ngram_range': (1, 3)}
 Score:0.4965873015873016
Parameters: {'min_df': 3, 'max_features': 1000000, 'ngram_range': (1, 4)}
 Score:0.4957142857142857
Parameters: {'min_df': 5, 'max_features': 1000000, 'ngram_range': (1, 2)}
 Score:0.48507936507936505
Parameters: {'min_df': 5, 'max_features': 1000000, 'ngram_range': (1, 3)}
 Score:0.48563492063492064
Parameters: {'min_df': 5, 'max_features': 1000000, 'ngram_range': (1, 4)}
 Score:0.4847619047619048